### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [zopefoundation/zope.hookable#18]
Problem
---------
On aarch64, ‘pip install zope.hookable’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install zope.hookable’ should download the wheels from pypi.

@jamadden Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by odidev** [comment]
It looks that you are building the wheel using **Travis-ci**. Shall I add the wheel in Travis-ci or is there any plans to move to github actions?

**Comment by icemac** [comment]
The plan is to move all zopefoundation repositories to GHA and to use a template for the actions configuration which contains support for aarch64 wheels.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.hookable/5.1.0/#files. The wheels should appear in some minutes after being generated by the CI systems.
