### ISSUE TITLE
Automate Windows wheels with appveyor

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.hookable#4]
zope.hookable contains C extensions which means pip installing it on Windows causes pain.

We could copy appveyor configs from e.g. zope.interface and set up automated wheel builds.

**Comment by jamadden** [comment]
I noticed that zope.wineggbuilder has started uploading artifacts for the current release...starting with artifacts for Python 3.3, which was dropped from the list of supported platforms. 🤷‍♂️

**Comment by mgedmin** [comment]
zope.wineggbuilder is the user used by winbot.zope.org to upload eggs, not wheels.  Also, as you've already noticed, it doesn't support any of the modern Python 3 versions.

I think the consensus is that it's much easier to set up appveyor than to [maintain winbot](https://github.com/zopefoundation/zope.wineggbuilder/issues).

I have an appveyor account and I know the zope.wheelbuilder PyPI user's password, so in theory I can set this up.  In practice burnout is a thing.  I can still find it in myself to log in into appveyor and add this repo, if somebody would submit a PR with an appveyor.yml.  Luckily, appveyor's secure variables are encrypted for a particular appveyor's account -- rather than a particular github repo -- so one can copy the encrypted value from one project to another.

**Comment by mgedmin** [comment]
I enabled appveyor for zope.hookable, with the setting to ignore branches without an appveyor.yml.

**Comment by mgedmin** [comment]
(Sometimes talking about doing things enables me to overcome my burnout and actually do things.)

**Comment by mgedmin** [comment]
I had a trick for doing retroactive appveyor builds for existing releases:

- create new branch based on the tag you want to build
- add a copy of the appveyor.yml from master
- edit appveyor.yml and adjust the condition that only builds tags
- push the branch to github, wait for an appveyor build that will upload the wheel files to pypih
- delete the branch on github (and locally)

**Comment by mgedmin** [comment]
Welp, twine upload successfully uploads the wheel, but appveyor thinks it failed.
![ekrano nuotrauka is 2017-07-27 17-00-30](https://user-images.githubusercontent.com/159967/28674125-28e36f2c-72ed-11e7-9f41-13b7d67846e2.png)

I'm not sure why -- because twine prints the progress bar to the standard error?  That would be silly.
