### ISSUE TITLE
Proxy the `original` __doc__?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.hookable#6]
Currently, any docstring from the hooked object is not available, in either the Python or C implementation:
```pycon
In [1]: def foo():
   ...:     "A foo"
   ...:

In [2]: from zope.hookable import hookable

In [3]: foo.__doc__
Out[3]: 'A foo'

In [4]: hookable
Out[4]: zope.hookable.hookable

In [5]: hooked = hookable(foo)

In [6]: hooked
Out[6]: <zope.hookable.hookable at 0x105759fd0>

In [7]: hooked.__doc__
Out[7]: 'Callable objects that support being overridden'

In [8]: from zope.hookable import _py_hookable

In [9]: hooked = _py_hookable(foo)

In [10]: hooked.__doc__
```

This makes hooked objects hard to document with sphinx and autodoc. This is especially true because you can't assign to `__doc__` of either object.

Can they be changed to automatically expose the `__doc__` of their (original?) implementation function?

If you do that you can use `.. autofunction:: the.hooked.function` (it won't be picked up by `.. automodule::` because it's not any kind of recognized type; treating it like a constant or data value and using the `#: special comments` doesn't work either).

If you format your docstring so the first line is a signature, you can stop there. If you don't, you'll get a warning that the object has no `__bases__`; you can ignore that or you can add one if the warning bothers you. For full generality (that I've found so far) you need to expose both `__bases__` and `__dict__`. I do this with a subclass:

```python
class _hookable(_base_hookable):
    __doc__ = property(lambda self: self.original.__doc__)
    __bases__ = property(lambda _: ())
    __dict__ = property(lambda _: None)
```

But I imagine most people would be happy to just have them get documented and ignore the warning.

**Comment by mgedmin** [comment]
:+1:

**Comment by jamadden** [comment]
I know how to do this in the Python implementation, but I'm not entirely sure how to do it for the C version yet; I'll have to research that.
